---
- name: Login for token 
  hosts: [rSeries]
  gather_facts: no
  connection: local 

  tasks:

  - name: Login via uri 
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-system:system/aaa'
      return_content: true 
      force_basic_auth: true
      method: GET
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      headers:
        Content-Type: application/yang-data+json
      validate_certs: false
    register: token

  - name: Debug 
    ansible.builtin.debug:
      var: token.x_auth_token

  - name: Get Tenant info 
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/f5-tenants:tenants'
      return_content: true 
      method: GET
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
    register: tenant 

  - name: Show Tenant 
    ansible.builtin.debug: 
      var: tenant

  - name: Get VLAN info 
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-vlan:vlans'
      return_content: true 
      method: GET
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
    register: vlan

  - name: Show Tenant 
    ansible.builtin.debug: 
      var: vlan['json']['openconfig-vlan:vlans']['vlan']